### ISSUE TITLE
Working with 0.4?

### ISSUE THREAD

**Issue by bogri** [fritz-smh/domogik-plugin-yi#1]
Hi,
I'm trying to install the plugin on latest Domogik, but when installing it after cloning the repo I'm having some issues. I've done:

cd /var/lib/domogik/domogik_packages
sudo ln -s /home/dd/domogik/domogik-plugin-yi plugin_yi
sudo dmg_package -i /home/dd/domogik/domogik-plugin-yi

and I'm getting:

Install a package from a folder : /home/dd/domogik/domogik-plugin-yi
Error while reading the json file '/home/dd/domogik/domogik-plugin-yi/info.json' : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.2/src/domogik/bin/package.py", line 505, in is_json_ok
    pkg_json = PackageJson(path = json_file)
  File "/opt/dmg/domogik-0.4.2/src/domogik/common/packagejson.py", line 145, in **init**
    raise PackageException(exp.value)
PackageException: "Error validating the json: key 'xpl_command' not found in command speak"

Any ideas?

**Comment by fritz-smh** [comment]
Hi,

It does not work with domogik 0.4.2. The minimal release required is 0.5.0 (the develop branch).

The error is indeed not clear in 0.4.2!

**Comment by tikismoke** [comment]
Related to https://github.com/domogik/domogik/issues/341
